Fix ping parser
We've got a lot of TypeError `parser(...) is not a function`
It's due to the number of Sedy installation from Hacker News.

This commit aims to fix the response to the GitHub `ping` event.